name: CI/CD

# Controls when the workflow will run
on:
  # Activates the workflow; then there is a push to the main or master branch
  push:
    # branches: [main, master]

  # allows you to manually execute this pipeline from the Actions tab.
  workflow_dispatch:

# A workflow run consists of one or more jobs that can be executed either sequentially or concurrently.
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set Up Python
        uses: actions/setup-python@v3 

      - name: Insatall Dependencies
        run:  pip install -r requirements.txt  # install requirements to enable GitHub run tests

      - name: Run Backend Tests
        run:  |
              python3 python/test/test.py 
              python3 python/test/unitTest.py 
              pytest python/test/test.py
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use the appropriate Node.js version

      - name: Install frontend dependencies
        run: npm install

      - name: Start the server
        run: npm run cy:start &

      - name: Run Cypress tests
        run: npm run cy:run
